---
- name: Check if nftables is installed
  command: which nft
  register: nft_check
  ignore_errors: true

- name: Fail if nftables is not available
  fail:
    msg: "nftables not found! Aborting playbook."
  when: nft_check.rc != 0

- name: Make Forwarder service
  template:
    src: forward.service.j2
    dest: /etc/systemd/system/forward.service
    mode: 0644
    owner: root
    group: root
  changed_when: true
  notify:
    - Enable Forwarder
