---
enable_easytier: true

easytier_version: v2.1.2

easytier_dir: "/opt/nomad/easytier"

easytier_port: 4097 

## Supported protocols: udp, tcp, ws, wss
easytier_protocol: udp

## Static IP configuration
easytier_client_ipv4: 10.44.44.1
easytier_server_ipv4: 10.44.44.2

## Generate a random secret: `openssl rand -hex 6``
easytier_secret: 5f67777d658f

easytier_encryption: false

easytier_multithread: true

easytier_ipv6: false

easytier_reverse: true

easytier_txqueuelen: 1000

